# Generated by Django 4.1.7 on 2023-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_notes_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
