# Generated by Django 4.1.7 on 2023-02-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_notes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='typeN',
            field=models.CharField(blank=True, choices=[('A', 'Assignment'), ('N', 'Notes'), ('E', 'Experiment')], max_length=50, null=True),
        ),
    ]
