# Generated by Django 4.1.7 on 2023-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_notes_typen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='name',
        ),
        migrations.AddField(
            model_name='notes',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
