# Generated by Django 4.1.7 on 2023-02-23 16:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_remove_notes_name_notes_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='docid',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='mod', unique=True),
        ),
    ]
