# Generated by Django 4.1.7 on 2023-02-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_notes_docid_alter_notes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacherurl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
