# Generated by Django 4.1.7 on 2023-02-25 10:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_subject_teacherurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogapp.subject'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='mod',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='sub', unique=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='typeN',
            field=models.CharField(blank=True, choices=[('Assignment', 'Assignment'), ('Experiment', 'Experiment'), ('Notes', 'Notes')], max_length=50, null=True),
        ),
    ]
