# Generated by Django 4.1.7 on 2023-03-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_notes_sub_alter_notes_mod_alter_notes_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='typeN',
            field=models.CharField(blank=True, choices=[('Assignment', 'Assignment'), ('Experiment', 'Experiment'), ('Notes', 'Notes'), ('ReferenceBook', 'Reference Book'), ('LectureSlides', 'Lecture Slides'), ('PYQ', 'PYQ')], max_length=50, null=True),
        ),
    ]
