# Generated by Django 4.1.7 on 2023-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_notes_ndetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='nDetail',
            field=models.CharField(blank=True, default='<django.db.models.fields.related.ForeignKey>+ Module - <django.db.models.fields.CharField> - <django.db.models.fields.CharField> by <django.db.models.fields.related.ForeignKey>', max_length=100, null=True),
        ),
    ]
