# Generated by Django 4.1.7 on 2023-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0018_useraccount_coins_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='coins_scored',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
