# Generated by Django 4.1.7 on 2023-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0020_alter_useraccount_coins_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
