# Generated by Django 4.1.7 on 2023-03-25 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_notes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='likes',
        ),
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.ManyToManyField(related_name='notes_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
