# Generated by Django 4.1.7 on 2023-03-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0022_remove_notes_likes_notes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='nDetail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
