# Generated by Django 4.1.7 on 2023-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0024_notes_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='subImage/'),
        ),
    ]
