# Generated by Django 4.1.7 on 2023-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0025_subject_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
