# Generated by Django 4.1.7 on 2023-03-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0026_notes_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
