# Generated by Django 4.1.7 on 2023-03-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0027_useraccount_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='views',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
