# Generated by Django 4.1.7 on 2023-03-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0029_alter_notes_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='blogapp.notes'),
        ),
    ]
