# Generated by Django 4.1.7 on 2023-03-31 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0032_alter_comment_slug_cmntreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmntreply',
            name='cmtRply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cmntreply',
            name='frR',
            field=models.TextField(),
        ),
    ]
